services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    env_file:
      - .env
    volumes:
      - /mongodbData:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy

  nginx:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    networks:
      - mynetwork
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - mynetwork
    depends_on:
      - backend

networks:
  mynetwork:
    driver: bridge
